// <auto-generated />
using System;
using ConversorBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConversorBack.Migrations
{
    [DbContext(typeof(ConversorDeMonedaContext))]
    [Migration("20241116221603_ConversorDB")]
    partial class ConversorDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("ConversorBack.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("IC")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Currencys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ARS",
                            IC = 0.0050000000000000001,
                            Name = "Peso Argentino",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USD",
                            IC = 1.0,
                            Name = "US Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EUR",
                            IC = 1.1000000000000001,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 4,
                            Code = "GBP",
                            IC = 1.3,
                            Name = "British Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 5,
                            Code = "JPY",
                            IC = 0.0070000000000000001,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CAD",
                            IC = 0.75,
                            Name = "Canadian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AUD",
                            IC = 0.71999999999999997,
                            Name = "Australian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CHF",
                            IC = 1.05,
                            Name = "Swiss Franc",
                            Symbol = "$"
                        });
                });

            modelBuilder.Entity("ConversorBack.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MaxConversions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxConversions = 10ul,
                            Type = "Free"
                        },
                        new
                        {
                            Id = 2,
                            MaxConversions = 100ul,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 3,
                            MaxConversions = 999ul,
                            Type = "Pro"
                        });
                });

            modelBuilder.Entity("ConversorBack.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TotalConversions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.com",
                            Password = "123456",
                            Role = 0,
                            SubscriptionId = 3,
                            TotalConversions = 999ul,
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
